name: Packaging and tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  packaging:
    name: build
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        poetry-version: [1.0, 1.1.11]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

  # check-coverage:
    # name: Check coverage
    # strategy:
      # fail-fast: false
      # matrix:
        # python-version: [3.6, 3.7, 3.8]
        # poetry-version: [1.0, 1.1.11]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    # steps:
      # - name: Check out Git repository
        # uses: actions/checkout@v2

      # - name: Set up Python
        # uses: actions/setup-python@v2
        # with:
          # python-version: ${{ matrix.python-version }}
      
      # - name: Run image
        # uses: abatilo/actions-poetry@v2.0.0
        # with:
          # poetry-version: ${{ matrix.poetry-version }}
      
      # - name: Install Python dependencies
        # run: pip install pytest coverage coverage-badge

      # - name: Run coverage
        # run: |
          # coverage run --source=pommesdispatch -m pytest --junitxml=report.xml
          # coverage report -m
          # coverage html
          # coverage-badge
