name: Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  check-coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install pytest coverage coverage-badge

      - name: Run coverage
        run: |
          coverage run --source=pommesdispatch -m pytest --junitxml=report.xml
          coverage report -m
          coverage html
          coverage-badge